### ISSUE TITLE
Consider setting theme automatically (or only having dark theme)

### ISSUE THREAD

**Issue by wbamberg** [openwebdocs/owd-website#1]
(See also https://github.com/openwebdocs/website-old/pull/20 and https://github.com/openwebdocs/website-old/issues/19#issuecomment-1090379710 in the old site.)

I don't know if this is true but I had heard that if we store the user's theme choice we have to ask their consent. We could avoid this issue (and the need for a button) by just using the system preference via `prefers-color-scheme`.

Alternatively I'd be happy for us just to use the dark theme, which I think looks great.

**Comment by queengooborg** [comment]
I'd be +1 for dark theme only; light themes hurt my eyes and it'd save development time.  ;P

AFAIK we only need to ask permission for storing _cookies_ to save user preferences, but we're using local storage instead.  So, I think we should be good?

**Comment by teoli2003** [comment]
I think we should go for `prefers-color-scheme`: I prefer light themes, except in the obscurity. I think it is a good proxy: if your OS is using one, display a dark theme, if it is using a light theme do the same.

For storing _stuff_. This depends of the country, I guess. So, if we can avoid it… (These permissions pop-ups are really annoying)

**Comment by queengooborg** [comment]
I did some more research into this, and it looks like `localStorage` is indeed covered by EU's GPDR laws in the same way cookies are.  However, from what I researched, it appears that consent for cookies "shall not prevent any technical storage or access for the sole purpose of carrying out the transmission of a communication over an electronic communications network, or as strictly necessary in order for the provider of an information society service explicitly requested by the subscriber or user to provide the service."  In the [Stack Exchange post](https://law.stackexchange.com/a/30766), the answer author cites examples from the UK's ICO where remembering a user's shopping cart items while they browse through the websites is considered an exception, because it is "strictly necessary to provide the service the user requests [...] and so the exception would apply and no consent would be required."  The answer author also cites user logins and keeping the user logged in as an exception, as the user had requested to remain logged in.

So based upon this, it sounds like a user input to switch between dark and light themes falls under this exception, as it is strictly necessary to ensure the site will display in the user's requested theme.
